# Generated by Django 4.1.3 on 2023-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_app", "0002_profile_notificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="notificationToken",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
