# Generated by Django 4.1.3 on 2022-11-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_app", "0002_category_product_profile_cityx_profile_cityy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cityX",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cityY",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(upload_to="profile_pics"),
        ),
    ]
